# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Publish docker

on:
  schedule:
    - cron: '39 12 * * *'
  push:
    branches: 
    - main
    tags:
    - '*'

jobs:
  docker-build:
    runs-on: ubuntu-latest
    needs: deploy-package
    steps:
    - uses: actions/checkout@v3
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Test
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}
    - name: Log in to Docker Hub
      run: |
            echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: gawsoft/aws-node-chrome
    - name: Build the Docker image
      run: |
            VERSION=$RELEASE_VERSION
            docker image build -t gawsoft/aws-node-chrome:$VERSION .
            VERSION=`docker run --name=tmp --rm --entrypoint=/bin/sh gawsoft/aws-node-chrome:$VERSION -c "cat /node-version.txt /chrome-version.txt" | tr '\n' '-'`
            docker container rm --force tmp || true
            docker image push gawsoft/aws-node-chrome:$VERSION
            # Publish latest
            docker image tag gawsoft/aws-node-chrome:$VERSION gawsoft/aws-node-chrome:latest
            docker image push gawsoft/aws-node-chrome:latest
        